name: bloc_rest_api
description: A generic bloc package to implement REST APIs easily in flutter.
version: 0.4.0+1
homepage: https://github.com/muhammadidrees/bloc_rest_api

environment: 
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  http: ^0.12.2
  hydrated_bloc: ^7.0.0
  meta: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  pedantic: ^1.9.2
  bloc_test: ^8.0.2

flutter:
